Split common crest platform homer and hs-prov
This adds a generic crest platform package (crest), which can be used
by other packages to create RESTful HTTP interfaces to Cassandra.

Homer and homestead-prov are then ported to this new platform, so
that they use the installed generic crest package, rather than
including their own copy.  On CW-AIO systems, the crest package
is thus shared.

diff --git a/debian/crest.prerm b/debian/crest.prerm
--- a/debian/crest.prerm
+++ b/debian/crest.prerm
@@ -1,4 +1,6 @@
-# @file connection.py
+#!/bin/sh
+
+# @file crest.prerm
 #
 # Project Clearwater - IMS in the Cloud
 # Copyright (C) 2013  Metaswitch Networks Ltd
@@ -32,30 +34,41 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
+#
+# see: dh_installdeb(1)
 
-import logging
-import threading
-from metaswitch.crest import settings
-import cql
+set -e
 
-_log = logging.getLogger("crest.connection")
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-thread_local = threading.local()
-thread_local.connections = {}
+CREST_DIR=/usr/share/clearwater/crest
 
-def get_or_create(keyspace):
-    connection = thread_local.connections.get(keyspace)
+case "$1" in
+    remove|upgrade|deconfigure)
+        rm -rf $CREST_DIR/env
+    ;;
 
-    if not connection:
-        _log.info("Connecting to Cassandra on %s", settings.CASS_HOST)
-        connection = cql.connect(settings.CASS_HOST,
-                                 settings.CASS_PORT,
-                                 keyspace,
-                                 cql_version='2.0.0')
-        assert connection
-        thread_local.connections[keyspace] = connection
-    return connection
+    failed-upgrade)
+    ;;
 
-def cursor(keyspace, *args, **kwargs):
-    connection = get_or_create(keyspace)
-    return connection.cursor(*args, **kwargs)
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
