Create homer-cassandra and homestead-prov-cassandra packages

diff --git a/debian/homer-cassandra.postinst b/debian/homer-cassandra.postinst
--- a/debian/homer-cassandra.postinst
+++ b/debian/homer-cassandra.postinst
@@ -1,9 +1,9 @@
-#!/bin/bash
+#/bin/sh
 
-# @file homer
+# @file homer-cassandra.postinst
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2013 Metaswitch Networks Ltd
+# Copyright (C) 2016  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -34,20 +34,42 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-# Set default values which will be overwritten if they exist in /etc/clearwater/config
-cassandra_hostname="localhost" 
-. /etc/clearwater/config
+#
+# see: dh_installdeb(1)
 
-# Only modify local_settings if the home_domain, sprout_hostname and local_ip
-# are available (they might not be if shared_config hasn't been propagated
-# round the deployment yet). Homer will cyclically restart until this has
-# been set up correctly
-if [ -n "$home_domain" ] && [ -n "$sprout_hostname" ] && [ -n "$local_ip" ]
-then
-  function escape { echo $1 | sed -e 's/\//\\\//g' ; }
-  sed -e 's/^LOCAL_IP = .*$/LOCAL_IP = "'$(escape $local_ip)'"/g
-          s/^SIP_DIGEST_REALM = .*$/SIP_DIGEST_REALM = "'$(escape $home_domain)'"/g
-          s/^SPROUT_HOSTNAME = .*$/SPROUT_HOSTNAME = "'$(escape $sprout_hostname)'"/g
-          s/^CASS_HOST = .*$/CASS_HOST = "'$(escape $cassandra_hostname)'"/g' < /usr/share/clearwater/homer/templates/local_settings.py >/tmp/local_settings.py.$$
-  mv /tmp/local_settings.py.$$ /usr/share/clearwater/homer/local_settings.py
-fi
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+case "$1" in
+    configure)
+        # Restart clearwater-infrastructure in order to trigger the
+        # homer-cassandra script.
+        service clearwater-infrastructure restart
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+exit 0
