Create all-in-one node that can be booted from an AMI

diff --git a/debian/homer.postinst b/debian/homer.postinst
--- a/debian/homer.postinst
+++ b/debian/homer.postinst
@@ -68,9 +68,14 @@ case "$1" in
             $HOMER_DIR/env/bin/python $module/setup.py install
             cd -
         done
-        [ ! -f /etc/iptables/rules.v4 ] || cp /etc/iptables/rules.v4 /etc/iptables/rules.v4.pre-homer
-        cp $HOMER_DIR/iptables.rules /etc/iptables/rules.v4
-        service iptables-persistent restart
+        # If this install is on a node that already has ellis installed, do not replace the iprules - it needs port 80 more than homer
+        if ! dpkg-query -W -f='${Status} ${Version}\n' ellis > /dev/null 2>&1
+        then
+            [ ! -f /etc/iptables/rules.v4 ] || cp /etc/iptables/rules.v4 /etc/iptables/rules.v4.pre-homer
+            cp $HOMER_DIR/iptables.rules /etc/iptables/rules.v4
+            service iptables-persistent restart
+        fi
+
         /etc/clearwater/scripts/homer
         echo Connecting to Cassandra on localhost...
         if echo "describe KEYSPACE homer;" | cqlsh -3 localhost 2>/dev/null | grep -q "CREATE KEYSPACE homer"
@@ -87,10 +92,11 @@ case "$1" in
         # Start monit monitoring ourselves
         cp $HOMER_DIR/*.monit /etc/monit/conf.d/
         service monit restart
-        # Now tell monit to start us if it hasn't already.  The
-        # restart may not have happened yet, so monit may not yet have
-        # heard of us. In that case, start ourselves.
-        monit start homer || service homer start
+        # Restart homer.  Always do this by terminating homer so monit will
+        # restart it more-or-less immediately.  (monit restart seems to have
+        # significant lag.)
+        # Don't fail if it's already stopped.
+        service homer stop || /bin/true
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -102,9 +108,8 @@ case "$1" in
     ;;
 esac
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
+if [ -x "/etc/init.d/homer" ]; then
+        update-rc.d homer defaults 60 40 >/dev/null || exit $?
+fi
 
 exit 0
